language: ruby
rvm:
- 2.4.1
install: bundle install --deployment
cache:
  directories: vendor/bundle
script:
- bin/rails db:migrate RAILS_ENV=test
- bin/rails test
deploy:
  provider: heroku
  api_key:
    secure: l8dMl/wnZ+BCzh4Dbc2He7R6ZSKNYjnz02rkcvBpS69CbBHrnJ4OGed2HoofA6GC2sb2CnSi5TUCpKmQxm+RLZB4RHmpIfjHs6pWwrbKHnJRZgizz3QZWjfc3mfPkjXWzStugF8iluEQJZgh57fv8raPfKHpo+xPdXBzqLY3LBJTwo/y8K0Hk14akhoVXSCixlf6zp0y3I3ljtap/EFkSYiLv4uScQj9kGhHDu9prOnAZ1kA9wKGvn38zDWUB48OYj5ZJd9msxxi3HkR31jTJ7tDtTgfNzaoeV2gkJL0aGNPlXF7UBcTnpjVonxkSWxgHxY6JNQiOJdgAcb/UTkpDjlOWGVX+TjHEEfw+dt6EZuCCTQyIXd6KG9NiAB9C7kM1wp13XTRjXEOP8xOD4o5v6Pnywa3opmN7k2/rELvA0vgnDLrb3z5xmHExejf7CR5LtnqCsPozidwLWlhETfkaifK968l2AMH4hEyGJjl3kl79U8od7+dO3s7aJ1VYpi1jVzgAd3I2gnuhG+FYc+NGifhLbfok2FdSygbtya+0UW0W8/oJfVP71sxgsW0AXKdrPtDf+11Uufy2UFqWjPp6ETKmOk8zwY6MdJvIDD9f3feVukF+cUm0jRTcuTWK3/33oHajzo8nLsslclTjyrk2XJPNkUgHUEylyURx+3YBTQ=
  app: nameless-springs-98046
  on:
    repo: enpitut2017/kakei_gakuen
